#!/usr/bin/env bash
echo "== sync"

set -e


# check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix"
    exit 1
fi

# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove the folder if it already exists
rm -r $OUTPUT_DIR

# create output folder
mkdir -p "$OUTPUT_DIR"

# generate a random number (5–10) to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

# create NUM_FILES random files with random content
for ((i=1; i<=$NUM_FILES; i++)); do
    #Generate a random filename
    FILENAME="$OUTPUT_DIR/${2}_$i.txt"


    #Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$1/files